theme: jekyll-theme-cayman
title: Bosmina Integrative Delimitation
description: Supplementary Materials & Interactive Visualizations
baseurl: "/Bosmina"
url: "https://dmitrykarabanov.github.io"
permalink: pretty
author: Dmitry Karabanov
github_username: DmitryKarabanov

social:
  name: Dmitry Karabanov
  links:
    - https://www.researchgate.net/profile/Dmitry-Karabanov

lang: en

plugins:
  - jekyll-seo-tag  
